"""empty message

Revision ID: 348baf2541db
Revises: 
Create Date: 2022-08-20 10:59:00.519705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348baf2541db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorites__sagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=900), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('valoration', sa.String(length=250), nullable=True),
    sa.Column('cast_imagen', sa.String(length=250), nullable=True),
    sa.Column('studio_id', sa.String(length=250), nullable=True),
    sa.Column('duration', sa.String(length=250), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.create_table('favorites__peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sagapeli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sagas_id', sa.Integer(), nullable=False),
    sa.Column('peliculas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peliculas_id'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['sagas_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sagapeli')
    op.drop_table('favorites__peliculas')
    op.drop_table('peliculas')
    op.drop_table('favorites__sagas')
    op.drop_table('user')
    op.drop_table('sagas')
    op.drop_table('category')
    # ### end Alembic commands ###
