"""empty message

Revision ID: 5659e03f8547
Revises: 8461d444d40b
Create Date: 2022-08-05 10:48:43.947301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5659e03f8547'
down_revision = '8461d444d40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peliculas', sa.Column('imagen', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peliculas', 'imagen')
    # ### end Alembic commands ###
