"""empty message

Revision ID: 92d42fbd2ec5
Revises: 89c2c3fdfeef
Create Date: 2022-08-13 08:37:55.916022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d42fbd2ec5'
down_revision = '89c2c3fdfeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peliculas', 'title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=600),
               existing_nullable=False)
    op.alter_column('peliculas', 'valoration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('peliculas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peliculas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('peliculas', 'valoration',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('peliculas', 'title',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
