"""empty message

Revision ID: b5f291f5dc11
Revises: 
Create Date: 2022-08-22 04:03:18.337509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f291f5dc11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('populares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('vote_average', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.String(length=900), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proximamente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('vote_average', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.String(length=900), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toprated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('vote_average', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.String(length=900), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buscador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('populares_id', sa.Integer(), nullable=False),
    sa.Column('toprated_id', sa.Integer(), nullable=False),
    sa.Column('proximamente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['populares_id'], ['populares.id'], ),
    sa.ForeignKeyConstraint(['proximamente_id'], ['proximamente.id'], ),
    sa.ForeignKeyConstraint(['toprated_id'], ['toprated.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buscador')
    op.drop_table('toprated')
    op.drop_table('proximamente')
    op.drop_table('populares')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
